"""Add pass_secure

Revision ID: 4cd0047bb18b
Revises: 93b7ac7cbe0a
Create Date: 2018-09-17 11:06:59.855641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd0047bb18b'
down_revision = '93b7ac7cbe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_title', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'category')
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_title')
    # ### end Alembic commands ###
